
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-17T00:29:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "75d0c47ad5c1f28455aeed2d39fca59a816eb3a3",
 "version": "3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
