#!/usr/bin/env python
"""
Sharadar Data Management for Zipline
====================================

Simplified script for managing Sharadar equity data bundles.

Requirements:
- NASDAQ Data Link API key with Sharadar subscription
- Set environment variable: NASDAQ_DATA_LINK_API_KEY

Usage:
    # Download specific tickers
    python scripts/manage_sharadar.py ingest --tickers AAPL,MSFT,GOOGL,AMZN,TSLA

    # Download ALL US equities (10-30 min, 10-20 GB)
    python scripts/manage_sharadar.py ingest --all

    # Check bundle status
    python scripts/manage_sharadar.py status

    # Clean old bundle data
    python scripts/manage_sharadar.py clean --keep-last 3

Examples:
    # Small test bundle (5 stocks)
    export NASDAQ_DATA_LINK_API_KEY='your_key_here'
    python scripts/manage_sharadar.py ingest --tickers AAPL,MSFT,GOOGL,AMZN,TSLA

    # Full database (all US equities)
    python scripts/manage_sharadar.py ingest --all

    # Update existing bundle
    python scripts/manage_sharadar.py update
"""

import os
import sys
import argparse
import subprocess
from pathlib import Path
from datetime import datetime

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / 'src'))


class SharadarManager:
    """Manage Sharadar data bundles for Zipline."""

    BUNDLE_NAME = 'sharadar'

    def __init__(self):
        """Initialize the Sharadar manager."""
        self.api_key = os.environ.get('NASDAQ_DATA_LINK_API_KEY')
        self._check_api_key()
        self._ensure_extension()

    def _check_api_key(self):
        """Verify API key is set."""
        if not self.api_key:
            print("\n" + "="*70)
            print("ERROR: NASDAQ_DATA_LINK_API_KEY not set")
            print("="*70)
            print("\nSharadar requires a NASDAQ Data Link API key with premium subscription.")
            print("\nSetup instructions:")
            print("  1. Subscribe to Sharadar at: https://data.nasdaq.com/databases/SFA")
            print("  2. Get your API key from: https://data.nasdaq.com/account/profile")
            print("  3. Set environment variable:")
            print("       export NASDAQ_DATA_LINK_API_KEY='your_key_here'")
            print("     Or create .env file:")
            print("       echo 'NASDAQ_DATA_LINK_API_KEY=your_key_here' > .env")
            print()
            sys.exit(1)

    def _ensure_extension(self):
        """Ensure zipline extension file exists."""
        ext_file = Path.home() / '.zipline' / 'extension.py'

        if ext_file.exists():
            return

        print("\n" + "="*70)
        print("FIRST TIME SETUP: Creating zipline extension file")
        print("="*70)
        print(f"\nCreating: {ext_file}")

        # Create .zipline directory
        ext_file.parent.mkdir(parents=True, exist_ok=True)

        # Create extension.py with Sharadar bundle registration
        extension_content = '''"""
Zipline extension - Auto-loads Sharadar bundle.
Generated by manage_sharadar.py
"""
from zipline.data.bundles import register
from zipline.data.bundles.sharadar_bundle import sharadar_bundle

# Register default Sharadar bundle (all tickers)
register('sharadar', sharadar_bundle())

print("✓ Sharadar bundle registered")
'''
        ext_file.write_text(extension_content)
        print(f"✓ Created: {ext_file}\n")

    def ingest(self, tickers=None, download_all=False):
        """
        Download and ingest Sharadar data.

        Parameters
        ----------
        tickers : list of str, optional
            Specific tickers to download
        download_all : bool
            Download all US equities (overrides tickers)
        """
        print("\n" + "="*70)
        print("SHARADAR DATA INGESTION")
        print("="*70)
        print(f"\nTimestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"Bundle: {self.BUNDLE_NAME}")

        if download_all:
            print("Scope: ALL US EQUITIES (~13,000+ tickers)")
            print("\n⚠️  WARNING: Full database download")
            print("   - Download time: 10-30 minutes")
            print("   - Storage required: 10-20 GB")
            print("   - Recommended for production use only")

            response = input("\nContinue with full download? [y/N]: ")
            if response.lower() != 'y':
                print("\nAborted. Use --tickers for a smaller dataset.")
                return

            ticker_list = None

        elif tickers:
            ticker_list = [t.strip().upper() for t in tickers.split(',')]
            print(f"Scope: {len(ticker_list)} tickers")
            print(f"Tickers: {', '.join(ticker_list)}")
        else:
            print("\nERROR: Must specify --tickers or --all")
            print("Examples:")
            print("  --tickers AAPL,MSFT,GOOGL")
            print("  --all")
            sys.exit(1)

        print("\n" + "-"*70)
        print("Registering Sharadar bundle...")
        print("-"*70)

        # Register the bundle with specified tickers
        from zipline.data.bundles import register
        from zipline.data.bundles.sharadar_bundle import sharadar_bundle

        if ticker_list:
            register(self.BUNDLE_NAME, sharadar_bundle(tickers=ticker_list))
            print(f"✓ Registered with {len(ticker_list)} tickers")
        else:
            register(self.BUNDLE_NAME, sharadar_bundle())
            print("✓ Registered for all tickers")

        # Run ingestion
        print("\n" + "-"*70)
        print("Starting data download and ingestion...")
        print("-"*70)
        print("\nThis will:")
        print("  1. Download SEP table (daily prices)")
        print("  2. Download ACTIONS table (corporate actions)")
        print("  3. Process and store data in zipline format")
        print("\nPlease wait...\n")

        result = subprocess.run(
            ['zipline', 'ingest', '-b', self.BUNDLE_NAME],
            capture_output=False,
        )

        if result.returncode == 0:
            print("\n" + "="*70)
            print("✓ SUCCESS: Sharadar bundle is ready!")
            print("="*70)
            print("\nBundle name: sharadar")
            print("\nUse in backtests:")
            print("  zipline run -f strategy.py --bundle sharadar")
            print("\nOr in Python:")
            print("  run_algorithm(..., bundle='sharadar')")
            print()
        else:
            print("\n" + "="*70)
            print("❌ ERROR: Ingestion failed")
            print("="*70)
            print("\nCommon issues:")
            print("  1. API key invalid or expired")
            print("  2. No Sharadar subscription")
            print("  3. Network connection problems")
            print("  4. Data quality issues (gaps in source data)")
            print("\nCheck the error messages above for details.")
            print()
            sys.exit(1)

    def update(self):
        """Update existing bundle with latest data."""
        print("\n" + "="*70)
        print("UPDATING SHARADAR BUNDLE")
        print("="*70)
        print(f"\nTimestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"Bundle: {self.BUNDLE_NAME}")
        print("\nFetching latest data from NASDAQ Data Link...")
        print()

        result = subprocess.run(
            ['zipline', 'ingest', '-b', self.BUNDLE_NAME],
            capture_output=False,
        )

        if result.returncode == 0:
            print("\n✓ SUCCESS: Bundle updated with latest data!")
        else:
            print("\n❌ ERROR: Update failed")
            sys.exit(1)

    def status(self):
        """Show bundle status and information."""
        print("\n" + "="*70)
        print("SHARADAR BUNDLE STATUS")
        print("="*70)

        # Check if bundle exists
        bundle_dir = Path.home() / '.zipline' / 'data' / self.BUNDLE_NAME

        if not bundle_dir.exists():
            print("\n❌ Bundle not found")
            print("\nThe Sharadar bundle has not been ingested yet.")
            print("\nTo download data:")
            print("  python scripts/manage_sharadar.py ingest --tickers AAPL,MSFT,GOOGL")
            print()
            return

        print(f"\n✓ Bundle location: {bundle_dir}")

        # Get bundle info from zipline
        print("\nBundle details:")
        result = subprocess.run(
            ['zipline', 'bundles'],
            capture_output=True,
            text=True,
        )

        if result.returncode == 0:
            # Find sharadar in output
            for line in result.stdout.split('\n'):
                if 'sharadar' in line.lower():
                    print(f"  {line}")

        # Check database size
        asset_db = bundle_dir / 'assets-7.sqlite'
        if asset_db.exists():
            import sqlite3
            conn = sqlite3.connect(str(asset_db))
            cursor = conn.cursor()

            # Count assets
            cursor.execute("SELECT COUNT(*) FROM equities")
            asset_count = cursor.fetchone()[0]

            # Get date range
            cursor.execute("SELECT MIN(start_date), MAX(end_date) FROM equities")
            date_range = cursor.fetchone()

            conn.close()

            print(f"\nData summary:")
            print(f"  Assets: {asset_count:,} stocks")
            if date_range[0] and date_range[1]:
                print(f"  Date range: {date_range[0]} to {date_range[1]}")

        print("\nUsage:")
        print("  zipline run -f strategy.py --bundle sharadar")
        print()

    def clean(self, keep_last=3):
        """
        Clean old bundle ingestion data.

        Parameters
        ----------
        keep_last : int
            Number of recent ingestions to keep
        """
        print("\n" + "="*70)
        print("CLEANING SHARADAR BUNDLE")
        print("="*70)
        print(f"\nKeeping last {keep_last} ingestions")
        print("Removing older data...\n")

        result = subprocess.run(
            ['zipline', 'clean', '-b', self.BUNDLE_NAME, '--keep-last', str(keep_last)],
            capture_output=False,
        )

        if result.returncode == 0:
            print(f"\n✓ SUCCESS: Old data cleaned")
        else:
            print(f"\n❌ ERROR: Cleaning failed")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Manage Sharadar data for Zipline',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    subparsers = parser.add_subparsers(dest='command', help='Command to run')

    # Ingest command
    ingest_parser = subparsers.add_parser('ingest', help='Download and ingest Sharadar data')
    ingest_group = ingest_parser.add_mutually_exclusive_group(required=True)
    ingest_group.add_argument(
        '--tickers',
        help='Comma-separated list of tickers (e.g., AAPL,MSFT,GOOGL)',
    )
    ingest_group.add_argument(
        '--all',
        action='store_true',
        help='Download ALL US equities (~13,000 tickers, 10-20 GB)',
    )

    # Update command
    subparsers.add_parser('update', help='Update existing bundle with latest data')

    # Status command
    subparsers.add_parser('status', help='Show bundle status and information')

    # Clean command
    clean_parser = subparsers.add_parser('clean', help='Clean old bundle data')
    clean_parser.add_argument(
        '--keep-last',
        type=int,
        default=3,
        help='Number of recent ingestions to keep (default: 3)',
    )

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    # Create manager and execute command
    manager = SharadarManager()

    if args.command == 'ingest':
        manager.ingest(tickers=args.tickers, download_all=args.all)
    elif args.command == 'update':
        manager.update()
    elif args.command == 'status':
        manager.status()
    elif args.command == 'clean':
        manager.clean(keep_last=args.keep_last)


if __name__ == '__main__':
    main()
